import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import { ThemeProvider } from 'next-themes';
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import {UserProvider} from "@/utils/userContext"
import {ThemeProvider} from "@/context/ThemeContext"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <SessionProvider session={session}>
          <div className="mx-auto">
          <UserProvider>
            <Navbar />
            {children}
            </UserProvider>
          </div>
        </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
